---
sudo: required
dist: trusty
language: node_js
node_js:
  - "lts/*"

before_install:
  # set up awscli packages
  - pip install --user awscli

cache:
  directories:
    - node_modules

script:
  # - yarn test
  - yarn build

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
  bucket: clementdungler.com
  skip_cleanup: true
  region: eu-west-2
  local_dir: build

after_deploy:
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
